FROM alpine:3.20@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d as otelc_curl
RUN apk --update add curl

FROM otel/opentelemetry-collector:latest@sha256:dbf77b00f14fceb02453433c7bf9b3438d5723e8b9bd53d61bfe1522d8f7ba5b

COPY --from=otelc_curl / /

COPY ./otel-collector-config.yaml /etc/otel-collector-config.yaml
USER 0
RUN chmod o+r /etc/otel-collector-config.yaml
USER nobody
