name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        roleToken:
          - rg_oidc_akr_f55fe1127adjkkcn8ty6 # Actions Test, all repos, 15min, push rubygem
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          role-to-assume: '${{ matrix.roleToken }}'
          gem-server: 'https://oidc-api-token.rubygems.org'
      - name: Test token
        run: |
          curl -v --fail 'https://oidc-api-token.rubygems.org/api/v1/oidc/api_key_roles/${{ matrix.roleToken }}' -H 'Authorization: ${{ env.RUBYGEMS_API_KEY }}'
