name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        registry: ['docker', 'ecr-public']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full git history is checked out

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        if: matrix.registry == 'docker'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Login to Public ECR
        if: matrix.registry == 'ecr-public'
        uses: docker/login-action@v2
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools>=61 setuptools_scm

      - name: Get Version
        id: get_version
        run: |
          echo "VERSION=$(python -c 'import setuptools_scm; print(setuptools_scm.get_version())')" >> $GITHUB_ENV

      - name: Build and push version
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
          tags: |
            ${{ matrix.registry == 'docker' && 'logzio/trivy-to-logzio' || 'public.ecr.aws/logzio/trivy-to-logzio' }}:${{ github.event.release.tag_name }}
            ${{ matrix.registry == 'docker' && 'logzio/trivy-to-logzio' || 'public.ecr.aws/logzio/trivy-to-logzio' }}:latest
